"use client";

import { useQuery } from "@tanstack/react-query";
import { motion, useReducedMotion } from "motion/react";
import { Activity, ArrowRight, CalendarCheck, CheckCircle2, HeartHandshake, LockKeyhole, MessageSquareHeart, Pill, Search, ShieldCheck, Sparkles, Star, Stethoscope, Users } from "lucide-react";
import Link from "next/link";
import { DoctorCard } from "@/components/doctors/doctor-card";
import { SectionHeading } from "@/components/common/section-heading";
import { Button } from "@/components/ui/button";
import { Card, Skeleton } from "@/components/ui/core";
import { healthcareService } from "@/services/healthcare-service";

const specialties = [["Cardiology", Activity], ["Neurology", Sparkles], ["Orthopedics", Users], ["Pediatrics", HeartHandshake], ["Dermatology", ShieldCheck], ["Psychiatry", MessageSquareHeart], ["Gynecology", Users], ["General Medicine", Stethoscope]] as const;
const benefits = [["Verified clinicians", "Every listed professional passes a careful credential review.", ShieldCheck], ["Booking without friction", "Find an open time and confirm care in a few focused steps.", CalendarCheck], ["Payments built for trust", "Secure Stripe checkout with backend-confirmed payment status.", LockKeyhole], ["Care records in one place", "Appointments and digital prescriptions stay easy to find.", Pill]] as const;

export function HomePage() {
  const reduceMotion = useReducedMotion();
  const doctors = useQuery({ queryKey: ["featured-doctors"], queryFn: ({ signal }) => healthcareService.featuredDoctors(signal) });
  const statistics = useQuery({ queryKey: ["public-statistics"], queryFn: ({ signal }) => healthcareService.statistics(signal) });
  const reviews = useQuery({ queryKey: ["success-stories"], queryFn: ({ signal }) => healthcareService.reviews({ featured: "true", limit: 3 }, signal) });
  const reveal = reduceMotion ? {} : { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-80px" }, transition: { duration: .5 } };

  return <>
    <section className="relative overflow-hidden border-b border-border bg-[radial-gradient(circle_at_80%_20%,var(--primary-soft),transparent_35%)]"><div className="container-shell grid min-h-[680px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={reduceMotion ? false : { opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}><p className="eyebrow flex items-center gap-2"><span className="h-px w-8 bg-primary" /> Care, thoughtfully connected</p><h1 className="mt-5 max-w-3xl text-balance text-5xl font-extrabold leading-[1.08] tracking-[-.04em] sm:text-6xl">The right care, <span className="text-primary">right when life needs it.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Discover trusted doctors, reserve a convenient time, and manage the details of your care from one calm, secure place.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link href="/doctors"><Search size={18} />Find a doctor</Link></Button><Button size="lg" variant="outline" asChild><Link href="/doctors">Book an appointment<ArrowRight size={18} /></Link></Button></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-muted-foreground">{["Verified professionals", "Secure payments", "Easy scheduling"].map((item) => <span key={item} className="flex items-center gap-2"><CheckCircle2 size={17} className="text-success" />{item}</span>)}</div></motion.div><motion.div className="relative mx-auto w-full max-w-lg" initial={reduceMotion ? false : { opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .6, delay: .12 }}><div className="absolute -inset-6 rounded-[3rem] bg-gradient-to-br from-primary/15 to-secondary/10 blur-2xl" /><div className="relative rounded-[2rem] border border-white/60 bg-surface p-5 shadow-2xl dark:border-white/10"><div className="rounded-[1.5rem] bg-gradient-to-br from-[#dff6f1] via-[#eef9f8] to-[#e5f2fb] p-8 dark:from-[#123c39] dark:via-[#102d2c] dark:to-[#102637]"><div className="mx-auto grid aspect-square max-w-xs place-items-center rounded-full border-[24px] border-white/50 bg-primary-soft"><div className="relative grid size-40 place-items-center rounded-full bg-primary text-white shadow-xl shadow-primary/25"><Stethoscope size={72} strokeWidth={1.4} /><span className="absolute -right-4 top-4 grid size-14 place-items-center rounded-2xl bg-surface text-danger shadow-lg"><Activity /></span></div></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted p-4"><p className="text-xs text-muted-foreground">Next available</p><p className="mt-1 font-bold">Today · 4:30 PM</p></div><div className="rounded-2xl bg-primary-soft p-4"><p className="text-xs text-primary">Patient rating</p><p className="mt-1 flex items-center gap-1 font-bold"><Star className="fill-amber-400 text-amber-400" size={16} /> 4.9 average</p></div></div></div></motion.div></div></section>

    <section className="section-space"><div className="container-shell"><SectionHeading eyebrow="Specialized care" title="A clearer path to the expertise you need" description="Explore care by specialty and connect with a verified professional suited to your needs." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{specialties.map(([name, Icon], index) => <motion.div key={name} {...reveal} transition={{ duration: .4, delay: index * .035 }}><Link href={`/doctors?specialization=${encodeURIComponent(name)}`} className="group flex h-full flex-col items-center rounded-2xl border border-border bg-surface p-6 text-center shadow-card transition hover:-translate-y-1 hover:border-primary/40"><span className="grid size-14 place-items-center rounded-2xl bg-primary-soft text-primary transition group-hover:bg-primary group-hover:text-white"><Icon size={25} /></span><h3 className="mt-4 text-sm font-bold sm:text-base">{name}</h3><span className="mt-2 text-xs font-semibold text-primary opacity-0 transition group-hover:opacity-100">Explore care →</span></Link></motion.div>)}</div></div></section>

    <section className="section-space bg-muted/60"><div className="container-shell"><SectionHeading eyebrow="Trusted specialists" title="Care led by experience and empathy" description="Profiles below are loaded directly from verified doctor records." />{doctors.isPending ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-[470px]" />)}</div> : doctors.data?.length ? <motion.div {...reveal} className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{doctors.data.map((doctor) => <DoctorCard key={doctor.id} doctor={doctor} />)}</motion.div> : <EmptyApiState message="Featured doctors will appear as soon as the care directory is available." /> }<div className="mt-10 text-center"><Button variant="outline" asChild><Link href="/doctors">Browse all doctors <ArrowRight size={17} /></Link></Button></div></div></section>

    <section className="section-space"><div className="container-shell"><motion.div {...reveal} className="grid overflow-hidden rounded-[2rem] bg-[#0b4743] text-white lg:grid-cols-[.9fr_1.1fr]"><div className="p-8 sm:p-12"><p className="eyebrow !text-teal-300">Care you can count on</p><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">Healthcare feels better when every detail is connected.</h2><p className="mt-5 leading-7 text-teal-50/70">From choosing a professional to reviewing your prescription, MediCare Connect keeps each step clear and within reach.</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-2">{benefits.map(([title, body, Icon]) => <div key={title} className="bg-[#0b4743] p-7"><Icon className="text-teal-300" /><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-teal-50/65">{body}</p></div>)}</div></motion.div></div></section>

    <section className="section-space bg-muted/60"><div className="container-shell"><SectionHeading eyebrow="Impact in numbers" title="A growing network built around better care" />{statistics.data ? <motion.div {...reveal} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(statistics.data).map(([key, value]) => <Card key={key} className="p-7 text-center"><p className="text-4xl font-extrabold text-primary">{value.toLocaleString()}+</p><p className="mt-2 text-sm font-semibold capitalize text-muted-foreground">{key.replace(/([A-Z])/g, " $1")}</p></Card>)}</motion.div> : <EmptyApiState message="Live platform statistics are temporarily unavailable." compact />}</div></section>

    <section className="section-space"><div className="container-shell"><SectionHeading eyebrow="Patient stories" title="Real experiences, shared with confidence" />{reviews.data?.length ? <motion.div {...reveal} className="grid gap-5 lg:grid-cols-3">{reviews.data.map((review) => <Card key={review.id} className="p-7"><div className="flex gap-1 text-amber-400">{Array.from({ length: review.rating }).map((_, i) => <Star key={i} size={16} fill="currentColor" />)}</div><blockquote className="mt-5 leading-7">“{review.comment}”</blockquote><div className="mt-6 border-t border-border pt-4"><p className="font-bold">{review.patientName}</p><p className="text-sm text-muted-foreground">Patient of {review.doctorName}</p></div></Card>)}</motion.div> : <EmptyApiState message="Patient stories will appear when approved reviews are available." compact />}</div></section>
  </>;
}

function EmptyApiState({ message, compact = false }: { message: string; compact?: boolean }) {
  return <Card className={compact ? "p-8 text-center" : "p-12 text-center"}><HeartHandshake className="mx-auto text-primary" size={32} /><p className="mt-3 font-semibold">{message}</p><p className="mt-1 text-sm text-muted-foreground">Please check again shortly.</p></Card>;
}
