import { Globe2 as Facebook, Mail, MapPin, MessageCircle as Instagram, Phone, Share2 as Twitter } from "lucide-react";
import Link from "next/link";
import { Logo } from "@/components/common/logo";

const columns = [{ title: "Platform", links: [["Find doctors", "/doctors"], ["About us", "/about"], ["Contact", "/contact"]] }, { title: "For patients", links: [["Book appointment", "/doctors"], ["My appointments", "/dashboard/appointments"], ["Prescriptions", "/dashboard/prescriptions"]] }];

export function Footer() {
  return <footer className="mt-auto bg-[#092d2b] text-slate-300"><div className="container-shell grid gap-10 py-16 md:grid-cols-2 lg:grid-cols-4"><div><Logo light /><p className="mt-5 max-w-xs text-sm leading-7 text-slate-400">Thoughtful tools that make finding care, managing visits, and staying well feel refreshingly simple.</p><div className="mt-5 flex gap-2">{[Facebook, Twitter, Instagram].map((Icon, i) => <a key={i} href="#" aria-label="Social media" className="grid size-10 place-items-center rounded-full bg-white/8 transition hover:bg-primary"><Icon size={17} /></a>)}</div></div>{columns.map((column) => <div key={column.title}><h2 className="font-bold text-white">{column.title}</h2><ul className="mt-5 space-y-3 text-sm">{column.links.map(([label, href]) => <li key={href}><Link className="transition hover:text-white" href={href}>{label}</Link></li>)}</ul></div>)}<div><h2 className="font-bold text-white">Here when you need us</h2><ul className="mt-5 space-y-4 text-sm"><li className="flex gap-3"><Phone className="mt-0.5 text-teal-300" size={18} /><span><b className="block text-white">Emergency hotline</b>+880 9600 123 456</span></li><li className="flex gap-3"><Mail className="text-teal-300" size={18} />care@medicareconnect.com</li><li className="flex gap-3"><MapPin className="text-teal-300" size={18} />Dhaka, Bangladesh</li></ul></div></div><div className="border-t border-white/10"><div className="container-shell flex flex-col gap-2 py-6 text-xs text-slate-500 sm:flex-row sm:justify-between"><p>© {new Date().getFullYear()} MediCare Connect. All rights reserved.</p><p>Privacy · Terms · Accessibility</p></div></div></footer>;
}
